export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const FETCHING_USER = 'FETCHING_USER';
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
export const SET_PROJECTS = 'SET_PROJECTS';
export const SET_SIGNEDIN_USER = 'SET_SIGNEDIN_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
