module.exports = (app, Comment, requireToken, auth) => {
	app.post(
		'/api/comments/new',
		requireToken,
		auth.isLoggedIn,
		Comment.createComment
	);
	app.put(
		'/api/comments/edit/:id',
		requireToken,
		auth.isLoggedIn,
		Comment.updateComment
	);
	app.delete(
		'/api/comments/delete/:id',
		requireToken,
		auth.isLoggedIn,
		Comment.deleteComment
	);
};
